{% set name = "Quandl" %}
{% set version = "3.5.1" %}
{% set sha256 = "097faef59d16a6e470f61d55403e9d2ec2e4785ddf81ef5b092d843ff2850ed9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - pandas >=0.14
    - numpy >=1.8
    - requests >=2.7.0
    - inflection >=0.3.1
    - python-dateutil
    - six
    - more-itertools
    - pyopenssl  # [py27]
    - ndg-httpsclient  # [py27]
    - pyasn1  # [py27]

test:
  imports:
    - test

about:
  home: https://www.quandl.com/
  license: MIT
  license_file: LICENSE.txt
  license_family: MIT
  # have requested to add it to the upstream: https://github.com/quandl/quandl-python/issues/103
  # license_file: LICENSE.txt
  summary: Source for financial, economic, and alternative datasets.

  description: |
    The premier source for financial, economic, and alternative
    datasets, serving investment professionals.
  doc_url: https://www.quandl.com/docs-and-help
  dev_url: https://github.com/quandl/quandl-python

extra:
  recipe-maintainers:
    - alen12345
