appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ALdk79EPOOCK+9vH4EyHK8fbXE3f0P8xxPrMfO02wI8PsL9a2cor7W/cL3qnU3SYFIrYgPsHfJ35+K0n0sJoBXJY3wkkowVv9AGv3WvLpDxyUO3JtI1x0Ld7u/WgQAwD5cKDY11PiwyWK51wKikd55qAhMLuIahoUjfAgQq06wNT6Tuq0wwu4wRkqmq0fGuP2yPks9sdWqzVzFQ+fMIN9SAY8OlV8XdaCKPQtxKmR7OCHdJf9VbHVSFRxNpG/dtiQsQQ2FdU002QzfTOrHmUPfJrIYENbo7WFBak8whBVYD/Pk+LSWM+fJJPsiFkev6V69Nju5WNsKqq0BFNZuY1gZA3lW8rQ09qhBvMpn3b6+VzgWLLQKLPevO0n23y6xFPm62u/Raq99AdlZnLFEtYv2M1WXmFxTkw86u8qr5FCsySNtYpbp7s20iPwg+WeEkxBle9nGNyf54RAsDV51C3QfZBNeamwNYqtaJK1k48jIzyWk/VqlP7/9UJ1kH/0EtTXuGducA9Zyd9M50SyEFixZ1RWH/LCZ2FZcPzq+1zEnraWMIfJLz4XZWQcr95ghJLEIxSaI+2k+/eRYf7QzGe4ePcuIER4g4gBX6GUJVdWydtXeiCKoGkzMrPk6FihsSK5NSy13wXXoeIz24cDCdBrUc8Zdn/YTwWLxBmUgxrums=}
provider:
  win: azure
conda_forge_output_validation: true
